### ISSUE TITLE
Problem using some CLI commands

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/hassio-cli#83] opened 2018-06-02 07:40 UTC
Problem using some CLI commands when homeassistant config is broken:

```
core-ssh:~# hassio -d ha logs
DEBUG [CmdHomeassistant]: action->'logs', endpoint='logs', serverOverride->'', GET->'true', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'logs', serverOverride->'', get->'true', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'logs', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/logs', GET->'true', payload->''
DEBUG [RestCall]: ResponseBody->'2018-06-02 10:38:45 ERROR (SyncWorker_0) [homeassistant.util.yaml] mapping values are not allowed here
  in "/config/configuration.yaml", line 40, column 9
2018-06-02 10:38:45 ERROR (MainThread) [homeassistant.bootstrap] Error loading /config/configuration.yaml: mapping values are not allowed here
  in "/config/configuration.yaml", line 40, column 9
'
Error decoding json invalid character '-' after top-level value: 2018-06-02 10:38:45 ERROR (SyncWorker_0) [homeassistant.util.yaml] mapping values are not allowed here
  in "/config/configuration.yaml", line 40, column 9
2018-06-02 10:38:45 ERROR (MainThread) [homeassistant.bootstrap] Error loading /config/configuration.yaml: mapping values are not allowed here
  in "/config/configuration.yaml", line 40, column 9
```
```
core-ssh:~# hassio -d ha check
DEBUG [CmdHomeassistant]: action->'check', endpoint='check', serverOverride->'', GET->'false', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'check', serverOverride->'', get->'false', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'check', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/check', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": ""}'
ERROR
```
```
core-ssh:~# hassio -d ha stop
DEBUG [CmdHomeassistant]: action->'stop', endpoint='stop', serverOverride->'', GET->'false', options->'', rawjson->'false', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'stop', serverOverride->'', get->'false', Options->'', Filter->'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'stop', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/stop', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": null}'
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2f8720, 0x442000a440)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x390
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x4420132200, 0x24, 0x200, 0x0)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x404
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x345e94, 0xd, 0xfffffb6dde54, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x31c
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0x44200e8580)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x540
github.com/urfave/cli.HandleAction(0x2dc640, 0x372ff0, 0x44200e8580, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x118
github.com/urfave/cli.Command.Run(0x345e94, 0xd, 0x0, 0x0, 0x49a280, 0x1, 0x1, 0x350d84, 0x2f, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x7b0
github.com/urfave/cli.(*App).Run(0x4420102000, 0x442000a140, 0x4, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x950
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x150
```

**Comment by ryanm101** [comment] 2018-06-02 07:58
What is your `hassio --version`
What version of the OS are you running?
What is your HA version?

**Comment by ryanm101** [comment] 2018-06-02 07:59
I cant reproduce these errors but it is possible our systems dont match, hence the above questions

**Comment by ciotlosm** [comment] 2018-06-02 08:06
```
core-ssh:~# hassio --version
hassio version 1.3.1
```
Keep in mind the errors are when running CLI command AFTER breaking your `configuration.yaml`. 
I added an extra key in my `mqtt:`

**Comment by ryanm101** [comment] 2018-07-02 22:31
I added a random key to my config:
```
➜  /config git:(master) ✗ hassio ha check
ERROR
Testing configuration at /config
ERROR:homeassistant.util.yaml:while scanning a simple key
  in "/config/configuration.yaml", line 53, column 3
could not find expected ':'
  in "/config/configuration.yaml", line 55, column 1
Failed config
  General Errors: 
    - Error loading /config/configuration.yaml: while scanning a simple key
  in "/config/configuration.yaml", line 53, column 3
could not find expected ':'
  in "/config/configuration.yaml", line 55, column 1
Successful config (partial)
```

**Comment by ryanm101** [comment] 2018-07-02 22:33
and when i added the ':'

```
➜  /config git:(master) ✗ hassio ha check      
ERROR
Testing configuration at /config
Failed config
  mqtt: 
    - Invalid config for [mqtt]: [extra] is an invalid option for [mqtt]. Check: mqtt->mqtt->extra. (See /config/configuration.yaml, line 47). Please check the docs at https://home-assistant.io/components/mqtt/
```

**Comment by frenck** [comment] 2018-09-22 17:53
I've tested it and could not reproduce it as well. 
v1.4.0 has been released, which might fix related error.

For now, I'm closing this issue, to prevent chasing ghosts.

**Closed by frenck** 2018-09-22 17:53 UTC
